apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mojeeeb/smartops.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: smartops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 