apiVersion: v1
kind: Service
metadata:
  name: smartops-bot
  namespace: smartops
  labels:
    app: smartops-bot
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
  selector:
    app: smartops-bot 